# Generated by Django 4.2.7 on 2023-11-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmate',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
